# Generated by Django 5.2.2 on 2025-06-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_note', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
        ),
        migrations.AddField(
            model_name='notes',
            name='year',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=1),
        ),
    ]
