# Generated by Django 5.2.2 on 2025-06-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_note', '0005_notes_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE')], default='cse', max_length=10),
        ),
    ]
